### ISSUE TITLE
Make the go examples use http roundtrip implementation as a library

### ISSUE THREAD

**Issue by vigoo** [golemcloud/golem-examples#16]
Currently the golem examples are having a `roundtrip.go` which is the wasi-http implementation of Go's `http` library. We should not copy this file into each project created, rather we should be able to use the https://github.com/golemcloud/go-wasi-http repository as a library.

**Comment by vigoo** [comment]
Should we still do this? (test comment)

**Comment by rjtch** [comment]
hello @vigoo i would like to work on this task.

**Comment by vigoo** [comment]
Thank you!
